### ISSUE TITLE
Please update to 1.19.3

### ISSUE THREAD

**Issue by Defflix** [thecolonel63/server-side-replay-recorder#10]
It would be nice to see an update for Minecraft 1.19.3, as this is the last mod I need that is not updated for 1.19.3. What would be a rough estimate for this update?

**Comment by Fummowo** [comment]
yes, an update would be greatly appreciated :)
especially useful for monitoring and resolving conflicts :))

**Comment by thecolonel63** [comment]
I'll go ahead and get an update to 1.19.3 out asap

**Comment by thecolonel63** [comment]
Updated to 1.19.3

**Comment by Defflix** [comment]
tysm

**Comment by Fummowo** [comment]
Wow that was so fast! Thank you very much! ✧⁠\⁠(⁠>⁠o⁠<⁠)⁠ﾉ⁠✧
