### ISSUE TITLE
Suggestion: Command for Event Markers

### ISSUE THREAD

**Issue by Nincodedo** [thecolonel63/server-side-replay-recorder#12]
The Replay Mod has the ability to create Event Markers during a recording. Would it be possible to include a command that would create an Event Marker in all current recordings?

**Comment by mattymatty97** [comment]
future 1.19.4 version has a command for markers, we're currently testing if the port with the new features works as intended

**Comment by thecolonel63** [comment]
Implemented as the /replay marker command!
