### ISSUE TITLE
Question About Forge And 1.16x Support

### ISSUE THREAD

**Issue by ghost** [thecolonel63/server-side-replay-recorder#13]
I was wondering if you could backport this mod to older Minecraft versions such as 1.16x and if you can add Forge support.
I understand Forge in general can just flat out be hard to use time to time so if you can't backport or add Forge, it is fine.

**Comment by thecolonel63** [comment]
Normally I would be okay with backporting to older versions, but with a mod as complex as this one it just isn't feasible to keep updating old versions.

In addition, on the topic of a Forge version - I do not support Forge modding as it lacks several features in the coding process which make Fabric modding much easier to work with. Also, I do not have much experience with writing Forge mods for this reason, so if I wanted to I could not.
