### ISSUE TITLE
Backport to 1.17.1 + QOL changes

### ISSUE THREAD

**Issue by mattymatty97** [thecolonel63/server-side-replay-recorder#14]
As i cannot make a pull request to create a new branch i'll open a issue instead:

Form [my fork branch](https://github.com/mattymatty97/server-side-ReplayMod/tree/addGo):
Backported to 1.17.1
Qol:
- Moved Mixins to allow recording of Carpet Bots ( FakePlayers )
- changed settings to yaml format
- added main recording toggle
- added whitelist to recordable players
- added ingame command to toggle active status
- added ingame command to manage recordable players

planned as soon as i get more time to dig into minecraft networking:
- merging recordings in the same dimension ( or from a specified group of players ) into the same file ( to be able to record large projects that are bigger than 12x12 chunks )
- possibility to start stop recording w/o having to log out/in
- command to upload the replayfile to a temporary site ( like [tmpfiles.org](https://tmpfiles.org/) maybe )

**Comment by thecolonel63** [comment]
Wow. Just wow.

When I get the chance I will make sure your additions and changes make their way onto the main branch.

If there is anything I can do to allow you to make direct changes to my main branch, ask and I will do so when I have the time.

Thank you for your work on these changes.

**Comment by mattymatty97** [comment]
Hi, glad that you like my changes.
once i have time i can replicate the QOL on the 1.19 branch
the reason why was not able to make a pull request is that my branch is a 1.17 backport and i didn't want to push the backport to your 1.19 main brach.

If you can make a separate 1.17 branch on your side i can make the pull request there.


I play and administrate a TMC server and we often have to record big projects with bad connection so a must for us was to be able to record the Carpet bots as they wont disconnect randomly in the middle of the project.

**Comment by mattymatty97** [comment]
also in case you want to contact me my discord is: mattymatty#9621
