### ISSUE TITLE
[Suggestion] Ouput files to location outside the server files

### ISSUE THREAD

**Issue by Ahptt** [thecolonel63/server-side-replay-recorder#16]
I have an external drive located at /mnt/ssd1 which I would like to use to save the replay files to. I added this to my config but it still seems to be saving the files in the server directory. Is this possible already, or if not would it be difficult to implement? I commented on issue #8 as afk players are one reason I need more space to save these files. It would be nice to toggle this. If not, I can implement a script to do this for me. Thanks!

**Comment by thecolonel63** [comment]
From what I can recall, the saved location is relative to the current directory, and I'm not sure I added a way to make it not relative to the current directory. I'd recomment implementing a script like you mentioned until I have the chance to add that as a feature.

**Comment by mattymatty97** [comment]
future 1.19.4 version has the ability to write to a custom path ( if you specify an absolute path in the config instead of a relative one )
