### ISSUE TITLE
Update to 1.19.4?

### ISSUE THREAD

**Issue by Ahptt** [thecolonel63/server-side-replay-recorder#17]
Hello again! I'm loving this mod and the replay's I've captured thus far for my server. I was wondering if there was an ETA on the 1.19.4 update? I've been monitoring this repo to determine if there was an update coming but I haven't seen anything yet. Many thanks for this great mod.

**Comment by Jh16** [comment]
Any ETA for updating for 1.19.4? Simply changing the thing to 1.19.4 just causes the server to crash.

**Comment by lighthal** [comment]
While searching for ways to monitor players on my server, I came across this mod. However, it only supports versions prior to 1.19.4. It would be great if the mod could be updated for the latest version as it's a really useful tool!

**Comment by thecolonel63** [comment]
I am terribly sorry about not fixing this for so long - All I can say is that a series of things happened that have taken priority so far, but I can *hopefully* get this thing updated this weekend. I'm not closing the issue until I do update the mod though.

**Comment by thecolonel63** [comment]
Update: I merged an old-ish pull request for a 1.17 backport that also included new features. The person who did the pull request agreed to move the features over to the latest branch when they were ready, so as soon as the new features are added to the 1.19 branch, I'll update it to 1.19.4.

**Comment by mattymatty97** [comment]
Testings on the 1.19.4 port are on the way. hopefully we'll have everything working soon

**Comment by thecolonel63** [comment]
Finally done - Better late then never XD
