### ISSUE TITLE
[Enhancement] Option to ecord one big file with all players (useful on small servers)

### ISSUE THREAD

**Issue by Cyclopropinon** [thecolonel63/server-side-replay-recorder#21]
it would record everything into one big file
to make the file size not too big there can be a new file every hour

**Comment by Cyclopropinon** [comment]
also an option to disable item packets and particles to reduce the size even more

useful for a timelapse of a giant world eater with several afk-accounts

**Comment by mattymatty97** [comment]
There is currently no way to merge multiple player POVs into a single file.
but for the use case you pointed out ( world-eater ) the upcoming release has the ability to record an arbitrary large area of chunks without the need of online players, plus also support to record POV of carpet bots.

**Comment by mattymatty97** [comment]
also for the "new file every X time" sadly there is also no way to start a POV recording without the player disconnecting and reconnecting

EDIT:
i'am working on a theory on this but for now is too far from beeing applicable

**Comment by Cyclopropinon** [comment]
> also for the "new file every X time" sadly there is also no way to start a POV recording without the player disconnecting and reconnecting
> 
> EDIT: i'am working on a theory on this but for now is too far from beeing applicable

maybe u could make a fake carpet player every X time to start a new recording
would that be practical/efficient?

edit: also pls dont forget to implement an option to disable recording of some packets tyvm

**Comment by mattymatty97** [comment]
> maybe u could make a fake carpet player every X time to start a new recording

that can and should be done by external tools not by a mod that has the purpose of recording
you can easily make a timed script to run commands in console

**Comment by mattymatty97** [comment]
> also pls dont forget to implement an option to disable recording of some packets tyvm

sadly the packets change name depending on the environment ( developement / runtime )
so it would be difficult to allow arbitrary packets to be dropped

we'll see what we can do
for now region recordings already drop duplicated chunk and light update packets

**Comment by thecolonel63** [comment]
While not exactly the same as combining all the players recordings into one file, an equivalent now exists in the form of the region replay, allowing a large region to be recorded that isn't confined to one specific player.
