### ISSUE TITLE
contact for work

### ISSUE THREAD

**Issue by gumdum** [thecolonel63/server-side-replay-recorder#3]
Hi, wanting to contract you through fiverr/ upwork/ guru to expand on this.  using the chinese version of serverside replaymod. create a way to make a players mcpr server side file to be one file per  date (small adjustment of your code) and add ability for players to view (maybe edit with replaystudio hack?) on a website and download the final mp4. Or just output from mcpr to first person mp4. Ability to view through an http server is available in the other sreplaymod on githun gumdum@calvinellis.dev. 210-850-5676. fellow Texan in San Antonio

**Comment by thecolonel63** [comment]
I'm sorry, but I'm currently busy with other projects for a while and I don't have time to add any or all of the features you are requesting.

I do appreciate you reaching out and asking me, however.
