### ISSUE TITLE
Doesn't work on 1.18.2?

### ISSUE THREAD

**Issue by yuann3** [thecolonel63/server-side-replay-recorder#40]
I downloaded version v1.0.4 (for 1.18.2) of this mod on modrinth and put it in my server's mods folder. But the mod doesn't work correctly, it only creates the `.config ` file and doesn't start recording.

Server Minecraft version 1.18.2, fabric
Server OS: Linux CentOS 7

**Comment by thecolonel63** [comment]
That's because the latest features are not in older Minecraft versions.

If you want the latest features, you'll need the latest version of Minecraft.

I can't backport features right now to older versions. Sorry!
