### ISSUE TITLE
New User Help / README?

### ISSUE THREAD

**Issue by btanner** [thecolonel63/server-side-replay-recorder#42]
Hey, this tool looks terrific. I've been trying to understand how it works by reading the docs here:
https://modrinth.com/mod/server-side-replay-recorder/changelog

The thing that's not clear to me is where the files are stored? I've unpacked the JAR in the `/mods` folder of a 1.20.1 server on Apex Hosting that happens to be running fabric.

After restarting the server, the mod seems to be working. I can add users to the white list through op commands, and I can see those changes in the yml file in `/config`

That yml file has default settings, including:
`replay_folder_name: "replay_recordings"`

I can't find a folder anywhere on the server called `replay_recordings`. I've tried restarting, disconnecting/rejoining a few times, etc.
So I tried to make the folder `/replay_recordings` and `/mods/replay_recordings`, but none of that seems to have helped.

Could you advise what I'm missing here? In return, I promise to submit a PR with the start of a README after I get the hang of using the tool.

**Comment by thecolonel63** [comment]
Hello! I apologize for not having a proper docs page for the mod that would prevent issues like this from happening.

Have you set "recording_enabled" to true in the config?

**Comment by btanner** [comment]
Hehe. No. 🤦

**Comment by btanner** [comment]
Thanks a million. Works great. Nice when it's something easy :)

**Comment by thecolonel63** [comment]
No problem, happy to help!
