### ISSUE TITLE
[Question/Enhancement] simple voice chat support

### ISSUE THREAD

**Issue by helleputter** [thecolonel63/server-side-replay-recorder#44]
Is there compabillity for simple voice chat like the mod replay-voice-chat implements?
If not would you have plans to add it and would it be hard to do?

**Comment by thecolonel63** [comment]
It was discussed as a potential idea earlier and a pull request was put in for it, but it wasn't accepted and is as of right now not a planned feature.

**Comment by mattymatty97** [comment]
i'll have to correct on that. it is a planned feature but we/i have not had enough time to try and implement it properly.

the reason for why i decided to discard the PR was that i did not like the way it was implemented in there.

anyways if we'll ever implement it it's going to have a lot of  limitations as we can only save the audio that routes through the server and for example not the one from groups

**Comment by helleputter** [comment]
Is it this [PR](https://github.com/thecolonel63/server-side-replay-recorder/pull/28)?

The way i want to use it there would be no groups used so that limitation sounds fine.

Is there a specific way you would want to implement it that goes beyond your  comments on the PR and the described limitations? If i find the time i would like to try and help getting this feature implemented. So if i know what you want/don't want in the implementation I can take that into account.

Would a config option to enable/disbale the recording of the audio also help?
