### ISSUE TITLE
Server wont stop...

### ISSUE THREAD

**Issue by SavageTheUnicorn** [thecolonel63/server-side-replay-recorder#48]
The server has to be forcibly killed to restart it. The server gets stuck on "Waiting for all replays to finish saving" or whatever it says. How do I solve this? I do not have any players recording or targeted by the mod!

**Comment by thecolonel63** [comment]
Hi,

This is already covered by Issue 30.

For now, since you aren't targeting any players or recording any regions, I'd suggest you disable the mod by removing it from the mods folder while it isn't in use until this gets fixed.
