### ISSUE TITLE
Update to 1.19.2

### ISSUE THREAD

**Issue by JanBenicek** [thecolonel63/server-side-replay-recorder#5]
Please update mod to MC 1.19.2. I want to use this mod on my build server for record progress of all players, but mod is only for 1.19.

**Comment by JanBenicek** [comment]
Or you planning update mod to the MC 1.20 after released??

**Comment by thecolonel63** [comment]
I'll update this when I have time, hopefully sooner than later.

**Comment by kennycc137** [comment]
> I'll update this when I have time, hopefully sooner than later.

Awesome dude this mod is great thanks for making it
