### ISSUE TITLE
Server Crash On Start

### ISSUE THREAD

**Issue by jayceDoesStuff** [thecolonel63/server-side-replay-recorder#51]
Crashlog:
https://pastebin.com/cE1iavx8

After I installed the mod, the server crashes on start. I've tried reinstalling and deleting the config file, but it keeps crashing, saying that the injection failed.

**Comment by thecolonel63** [comment]
At a first glance, this appears to be caused by a conflict with Very Many Players. Can you try disabling VMP and checking again?

**Comment by jayceDoesStuff** [comment]
Yeah, it's working now, thanks!
