### ISSUE TITLE
Making it toggleble 

### ISSUE THREAD

**Issue by TheBo8os** [thecolonel63/server-side-replay-recorder#8]
I think it would be nice Qol to make it Toggleable
It may save space for the server incases where someone is afk
or abot is afk overnight
and would be nice to to able to toggle it without a server restart 
or maybe even per player Toggle

**Comment by thecolonel63** [comment]
I'll look into this and likely release an update some time between tomorrow and Sunday

**Comment by Ahptt** [comment]
Was this added? I looked for a configuration option but didn't see anything.

**Comment by thecolonel63** [comment]
Yeah sorry, I never had time to figure out how to make it work fully, so I never officially made a release. With the latest work that mattymatty has made on the branch, I suspect it'll be added soon-ish

**Comment by mattymatty97** [comment]
Can confirm this is gonna be in the new release:
- Global Toggle
- Per Player Toggle
- Commands to manage them ingame
