### ISSUE TITLE
Support offline mode

### ISSUE THREAD

**Issue by Libreh** [thecolonel63/server-side-replay-recorder#9]
I run 2 Fabric servers through Velocity and I would really appreciate if it you made this mod work with online-mode = false

**Comment by thecolonel63** [comment]
I'll see what I can do this weekend.

**Comment by Libreh** [comment]
Any progress?

**Comment by thecolonel63** [comment]
I've been preoccupied with other projects but I'll most likely get an update out in the next 32 hours or so

**Comment by thecolonel63** [comment]
I went ahead and made a push to support offline mode, but I'm still planning on adding a few features before the next release, so I haven't made a separate release yet.

You're more than welcome to clone it and build it yourself until I make that separate release.
